"use client";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { DollarSign, Shield, AlertTriangle } from "lucide-react";

export function FinanceWorkspace() {
  return (
    <div className="space-y-6">
      <Card className="bg-zinc-900 border-zinc-800">
        <CardHeader>
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-emerald-600/20 flex items-center justify-center">
              <DollarSign className="w-4 h-4 text-emerald-400" />
            </div>
            <div>
              <CardTitle className="text-sm text-zinc-200">Finance Invoice Generator Agent</CardTitle>
              <p className="text-[11px] text-zinc-500 mt-0.5">Model: openai/gpt-4o-mini via GitHub Models</p>
            </div>
            <Badge variant="outline" className="ml-auto border-emerald-500/30 text-emerald-400 bg-emerald-500/10 text-[11px]">Active</Badge>
          </div>
        </CardHeader>
        <CardContent className="space-y-5">
          <div className="grid grid-cols-2 gap-3">
            {[
              { label: "Tax Rate", value: "8.0%" },
              { label: "Invoice Format", value: "INV-XXXXXXXX" },
              { label: "Terms", value: "NET-30" },
              { label: "Currency", value: "USD" },
            ].map(({ label, value }) => (
              <div key={label} className="bg-zinc-800/50 border border-zinc-700/50 rounded-lg p-3">
                <p className="text-[10px] text-zinc-500">{label}</p>
                <p className="text-sm font-semibold text-zinc-200 mt-1">{value}</p>
              </div>
            ))}
          </div>

          {/* HITL Gate info */}
          <div className="bg-amber-950/20 border border-amber-700/30 rounded-lg p-4">
            <div className="flex items-center gap-2 mb-2">
              <AlertTriangle className="w-3.5 h-3.5 text-amber-400" />
              <span className="text-[11px] font-semibold uppercase tracking-widest text-amber-400">
                HITL Gate Active
              </span>
            </div>
            <p className="text-xs text-zinc-400 leading-relaxed">
              Invoices with <span className="text-amber-300 font-semibold">total_usd &gt; $1,000</span> trigger
              LangGraph&apos;s <code className="text-amber-300 text-[11px] bg-zinc-800 px-1 rounded">interrupt()</code> signal,
              suspending graph execution. The run waits in <code className="text-amber-300 text-[11px] bg-zinc-800 px-1 rounded">PENDING_APPROVAL</code> state
              until an operator approves or rejects via the HITL modal.
            </p>
          </div>

          {/* Auth chain */}
          <div>
            <p className="text-[11px] text-zinc-500 uppercase tracking-widest font-semibold mb-3">Authorisation chain</p>
            <div className="space-y-2">
              {[
                { icon: Shield, label: "Invoice generated by LLM", note: "8% tax applied automatically" },
                { icon: AlertTriangle, label: "Total > $1,000 → interrupt()", note: "LangGraph checkpoint saved" },
                { icon: DollarSign, label: "Operator approval received", note: "Command(resume=…) wakes the graph" },
              ].map(({ icon: Icon, label, note }, i) => (
                <div key={label} className="flex items-start gap-3">
                  <div className="flex flex-col items-center">
                    <div className="w-6 h-6 rounded-full bg-zinc-800 border border-zinc-700 flex items-center justify-center">
                      <Icon className="w-3 h-3 text-zinc-400" />
                    </div>
                    {i < 2 && <div className="w-px h-5 bg-zinc-800 mt-1" />}
                  </div>
                  <div className="pb-3">
                    <p className="text-xs font-medium text-zinc-200">{label}</p>
                    <p className="text-[11px] text-zinc-500 mt-0.5">{note}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
